package state

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"time"

	"github.com/thomkin/muro/internal/config"
)

// SandboxState is the lifecycle state of a sandbox.
type SandboxState string

const (
	StateRunning          SandboxState = "running"
	StateStopped          SandboxState = "stopped"
	StateReloadPending    SandboxState = "reload-pending"
	StateCrashed          SandboxState = "crashed"
	StateRestarting       SandboxState = "restarting"
	StateRestartExhausted SandboxState = "restart-exhausted"
)

// Sandbox is the daemon's live record of one running (or previously running)
// sandbox. ID is an internal storage key only — CLI-facing addressing uses
// Namespace/Name (DESIGN.md §9).
type Sandbox struct {
	ID        string   `json:"id"`
	Name      string   `json:"name"`
	Namespace string   `json:"namespace"`
	Profile   string   `json:"profile"`
	Agent     string   `json:"agent"`
	AgentArgs []string `json:"agent_args,omitempty"`
	// Env is this sandbox's launch-time environment, resolved once from the
	// launching profile's own Env field at Run time and persisted here —
	// the same "resolved once, carried forward" pattern every other
	// profile-derived field already uses. Previously this was NOT
	// persisted at all: buildLaunchSpec took it as a separate parameter
	// that Run passed profile.Env into but a plain Restart (and
	// watchLoop's crash-relaunch) always passed nil, silently losing every
	// profile env var — including ones a launch can depend on for
	// correctness (e.g. CLAUDE_CODE_BUBBLEWRAP) — on every restart after
	// the first. Confirmed as a real bug via a live restart reproducing
	// exactly that failure.
	Env           map[string]string `json:"env,omitempty"`
	PID           int               `json:"pid"`
	State         SandboxState      `json:"state"`
	StartedAt     time.Time         `json:"started_at"`
	Mounts        []config.Mount    `json:"mounts"`
	Tools         []config.Tool     `json:"tools"`
	AllowURLs     []string          `json:"allow_urls"`
	RestartPolicy string            `json:"restart_policy"`
	RestartCount  int               `json:"restart_count"`
	// GitPolicy is this sandbox's git tool-proxy grant, resolved once from
	// the launching profile's own Git field at Run time and persisted here
	// (the same "resolved once, carried forward" pattern Mounts/Tools/
	// AllowURLs already use) — so a Reattach after a murod restart still
	// knows the policy without needing the original profile file to still
	// exist unchanged.
	GitPolicy config.GitPolicy `json:"git_policy,omitempty"`

	// Audio records whether this sandbox was launched with audio-passthrough
	// enabled (internal/sandbox/audio.go) — resolved once from the launching
	// profile's own Audio field at Run time, same "resolved once, carried
	// forward" pattern as GitPolicy above. A plain bool needs no special
	// handling in Clone (the struct copy below already copies it).
	Audio bool `json:"audio,omitempty"`

	// ShimSocket, NetAddr, and SlirpPID let a restarted murod reconstruct
	// a live Handle for a sandbox it didn't itself launch (Stage 3 shim
	// lifecycle, internal/sandbox/shim.go) — PID alone is only enough to
	// check liveness (state.Reconcile), not to re-attach or correctly
	// tear the sandbox's network bridge down. ShimSocket is the Unix
	// socket path the sandbox's persistent shim process listens on for
	// attach; NetAddr is its bridged outbound loopback address
	// (internal/sandbox/network.go); SlirpPID is its slirp4netns bridge
	// process's PID, needed because a reconstructed Handle was never that
	// process's parent and so has no wait4(2)-based way to manage it,
	// only signal-by-PID.
	ShimSocket string `json:"shim_socket,omitempty"`
	NetAddr    string `json:"net_addr,omitempty"`
	SlirpPID   int    `json:"slirp_pid,omitempty"`

	// InjectSocket is the Unix socket path muro-shim listens on for pty
	// input injection (internal/sandbox/inject.go) — the inbound half of
	// the MQTT agent-to-agent bridge (DESIGN.md §8). Persisted, like
	// ShimSocket, so the daemon's inbox-message listener can dial it
	// directly from the Store without needing a live Handle at all — this
	// is what lets an inbox subscription re-delivering a message after a
	// murod restart still work even though Reattach (internal/sandbox/
	// bwrap.go) never repopulates this field on its reconstructed Handle.
	InjectSocket string `json:"inject_socket,omitempty"`

	// SessionID is a stable, per-sandbox-instance UUID generated once at
	// Run and never regenerated by Restart (with or without
	// fromProfile) — exposed inside the sandbox as $MURO_SESSION_ID and
	// substitutable into agent_args via a literal "{{SESSION_ID}}" token
	// (buildLaunchSpec, internal/sandbox/manager.go), since agent_args are
	// exec'd directly with no shell to expand an env var reference. Lets
	// an agent (e.g. Claude Code's --session-id) maintain one continuous
	// identity across restarts of the same sandbox, without muro needing
	// to understand what that identity is used for.
	SessionID string `json:"session_id,omitempty"`

	// PrivateDirs are the sandbox-internal paths this sandbox was launched
	// with fresh, sandbox-instance-private backing directories for
	// (resolved once from the launching profile's own PrivateDirs field,
	// same "resolved once, carried forward" pattern as GitPolicy/Audio) —
	// persisted so a later `muro sandbox delete` knows which private
	// directories it created and must remove.
	PrivateDirs []string `json:"private_dirs,omitempty"`

	// Worktrees are the git worktrees created for this sandbox's
	// worktree: true git policy repos (DESIGN.md §15) — one entry per such
	// repo, resolved once at Run/Restart(fromProfile) time by
	// internal/sandbox's resolveSandboxFieldsFromProfile and persisted here
	// so `muro sandbox show`, `muro sandbox merge`, and `muro sandbox
	// delete`'s unmerged-work guard all have what they need (the worktree's
	// real host path, its branch, and its base branch) without needing the
	// launching profile file to still exist unchanged.
	Worktrees []WorktreeInfo `json:"worktrees,omitempty"`
}

// WorktreeInfo records one git worktree DESIGN.md §15 created for this
// sandbox: MountPath is the sandbox-internal path it's mounted at (matches
// config.GitRepoPolicy.MountPath); Host is the worktree's own real path on
// the host (what's actually mounted, and what internal/worktree's
// functions operate on); RepoHost is the real source repo it was created
// from (config.GitRepoPolicy.Host) — where a merge actually lands; Branch
// is the muro-generated branch (agent/<namespace>/<name>) checked out in
// the worktree; BaseBranch is the branch it was created from and what it
// merges back into.
type WorktreeInfo struct {
	MountPath  string `json:"mount_path"`
	Host       string `json:"host"`
	RepoHost   string `json:"repo_host"`
	Branch     string `json:"branch"`
	BaseBranch string `json:"base_branch"`
}

// Clone returns a deep copy of sb — a shallow struct copy would still share
// the underlying arrays of Mounts/Tools/AllowURLs with the original, so a
// caller mutating a "copy" could still race with or corrupt the Store's
// internal state. Store uses Clone on every value crossing its API boundary
// (in via Put, out via Get/List) so callers never hold a pointer aliased to
// the Store's own map entries, however they mutate it (internal/sandbox's
// Manager found this the hard way via go test -race).
func (sb *Sandbox) Clone() *Sandbox {
	if sb == nil {
		return nil
	}
	out := *sb
	out.AgentArgs = append([]string(nil), sb.AgentArgs...)
	if sb.Env != nil {
		out.Env = make(map[string]string, len(sb.Env))
		for k, v := range sb.Env {
			out.Env[k] = v
		}
	}
	out.PrivateDirs = append([]string(nil), sb.PrivateDirs...)
	out.Mounts = append([]config.Mount(nil), sb.Mounts...)
	out.Tools = append([]config.Tool(nil), sb.Tools...)
	out.AllowURLs = append([]string(nil), sb.AllowURLs...)
	out.GitPolicy = config.GitPolicy{Repos: append([]config.GitRepoPolicy(nil), sb.GitPolicy.Repos...)}
	for i, repo := range out.GitPolicy.Repos {
		out.GitPolicy.Repos[i].AllowedBranches = append([]string(nil), repo.AllowedBranches...)
		out.GitPolicy.Repos[i].AllowedRemotes = append([]string(nil), repo.AllowedRemotes...)
	}
	out.Worktrees = append([]WorktreeInfo(nil), sb.Worktrees...)
	return &out
}

// NewID generates a unique internal sandbox id, e.g. "sb_8f2a1c9d".
func NewID() (string, error) {
	buf := make([]byte, 4)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("generate sandbox id: %w", err)
	}
	return "sb_" + hex.EncodeToString(buf), nil
}

// key is the Store's internal map key for a sandbox: "namespace/name".
func key(namespace, name string) string {
	return namespace + "/" + name
}
